/**
 * Registry of CPU scheduling algorithms exposed to the app shell.
 */
export const MLFQ_LEVEL_ALGORITHM_IDS = ['FCFS', 'SJF', 'SRTF', 'ROUND_ROBIN']

export const ALGORITHM_REGISTRY = [
  {
    id: 'FCFS',
    label: 'First Come, First Served',
    shortLabel: 'FCFS',
    description: 'Executes processes in arrival order with a simple, non-preemptive queue.',
    hasQuantum: false,
    hasAging: false,
    hasLevels: false,
    isPreemptive: false,
  },
  {
    id: 'SJF',
    label: 'Shortest Job First',
    shortLabel: 'SJF',
    description: 'Selects the process with the smallest next burst to reduce average wait time.',
    hasQuantum: false,
    hasAging: false,
    hasLevels: false,
    isPreemptive: false,
  },
  {
    id: 'SRTF',
    label: 'Shortest Remaining Time First',
    shortLabel: 'SRTF',
    description: 'A preemptive SJF variant that always favors the shortest remaining burst.',
    hasQuantum: false,
    hasAging: false,
    hasLevels: false,
    isPreemptive: true,
  },
  {
    id: 'PRIORITY',
    label: 'Priority Scheduling',
    shortLabel: 'PRIO',
    description: 'Ranks processes by priority while keeping the execution order non-preemptive.',
    hasQuantum: false,
    hasAging: true,
    hasLevels: false,
    isPreemptive: false,
  },
  {
    id: 'PRIORITY_PREEMPTIVE',
    label: 'Priority Scheduling - Preemptive',
    shortLabel: 'P-PRIO',
    description: 'Interrupts lower-priority work when a more urgent process becomes ready.',
    hasQuantum: false,
    hasAging: true,
    hasLevels: false,
    isPreemptive: true,
  },
  {
    id: 'ROUND_ROBIN',
    label: 'Round Robin',
    shortLabel: 'RR',
    description: 'Rotates ready processes through a fixed quantum for fair time slicing.',
    hasQuantum: true,
    hasAging: false,
    hasLevels: false,
    isPreemptive: true,
  },
  {
    id: 'MLFQ',
    label: 'Multi-Level Feedback Queue',
    shortLabel: 'MLFQ',
    description: 'Moves processes across priority levels based on behavior and runtime history.',
    hasQuantum: true,
    hasAging: true,
    hasLevels: true,
    isPreemptive: true,
    levelAlgorithmIds: MLFQ_LEVEL_ALGORITHM_IDS,
  },
]